name: Build V2
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  MODULE_PREFIX: gmsv
  MODULE_NAME: steamworks

jobs:
  linux64:
    runs-on: ubuntu-20.04
        
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'module'
          submodules: 'recursive'
        
      - name: 'Clone garrysmod_common'
        uses: actions/checkout@v2
        with:
          repository: 'danielga/garrysmod_common'
          ref: 'x86-64-support-sourcesdk'
          path: 'garrysmod_common'
          submodules: 'recursive'
          
      - name: 'Setup dirs'
        run: |
          mkdir -p out/Release
          mkdir -p out/Debug
          
      - name: 'Setup module'
        run: |
          export GARRYSMOD_COMMON=${{github.workspace}}/garrysmod_common
          cd module
          ./configure
      
      - name: '[x64] Build Release'
        run: |
          cd module/projects/linux/gmake/
          make -j2 config=release_x86_64
          mv x86_64/Release/${{env.MODULE_PREFIX}}_${{env.MODULE_NAME}}_linux64.dll ${{github.workspace}}/out/Release
          
      - name: '[x64] Build Debug'
        run: |
          cd module/projects/linux/gmake/
          make -j2 config=debug_x86_64
          mv x86_64/Debug/${{env.MODULE_PREFIX}}_${{env.MODULE_NAME}}_linux64.dll ${{github.workspace}}/out/Debug

      - name: Upload release build
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: out/Release/

      - name: Upload debug build
        uses: actions/upload-artifact@v2
        with:
          name: Debug
          path: out/Debug/

  linux:
    runs-on: ubuntu-20.04
        
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'module'
          submodules: 'recursive'
        
      - name: 'Clone garrysmod_common'
        uses: actions/checkout@v2
        with:
          repository: 'danielga/garrysmod_common'
          ref: 'x86-64-support-sourcesdk'
          path: 'garrysmod_common'
          submodules: 'recursive'
          
      - name: 'Setup dirs'
        run: |
          mkdir -p out/Release
          mkdir -p out/Debug
          
      - name: 'Install multilib'
        run: |
          sudo apt install gcc-multilib g++-multilib
          
      - name: 'Setup module'
        run: |
          export GARRYSMOD_COMMON=${{github.workspace}}/garrysmod_common
          cd module
          ./configure
          
      - name: '[x32] Build Release'
        run: |
          cd module/projects/linux/gmake/
          make -j2 config=release_x86
          mv x86/Release/${{env.MODULE_PREFIX}}_${{env.MODULE_NAME}}_linux.dll ${{github.workspace}}/out/Release
          
      - name: '[x32] Build Debug'
        run: |
          cd module/projects/linux/gmake/
          make -j2 config=debug_x86
          mv x86/Debug/${{env.MODULE_PREFIX}}_${{env.MODULE_NAME}}_linux.dll ${{github.workspace}}/out/Debug
          
      - name: Upload release build
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: out/Release/

      - name: Upload debug build
        uses: actions/upload-artifact@v2
        with:
          name: Debug
          path: out/Debug/

  win64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'module'
          submodules: 'recursive'

      - name: 'Clone garrysmod_common'
        uses: actions/checkout@v2
        with:
          repository: 'danielga/garrysmod_common'
          ref: 'x86-64-support-sourcesdk'
          path: 'garrysmod_common'
          submodules: 'recursive'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: 'Setup dirs'
        run: |
          New-Item -ItemType Directory -Force -Path .\out\Release
          New-Item -ItemType Directory -Force -Path .\out\Debug

      - name: 'Setup module'
        run: |
          $env:GARRYSMOD_COMMON = "${{github.workspace}}\garrysmod_common"
          cd module
          ./configure.bat
          
      - name: '[x64] Build Release'
        run: |
          cd module\projects\windows\vs2019
          msbuild.exe ${{env.MODULE_NAME}}.sln -property:Configuration=Release -property:Platform=x64 -m
          Move-Item x86_64\Release\${{env.MODULE_PREFIX}}_${{env.MODULE_NAME}}_win64.dll ${{github.workspace}}\out\Release

      - name: Upload release build
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: out/Release/

      - name: Upload debug build
        uses: actions/upload-artifact@v2
        with:
          name: Debug
          path: out/Debug/