name: Build library
on: [push, pull_request]

jobs:
  linux-64:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure
        run: ./configure
        
      - name: Build
        run: |
          cd projects/linux/gmake
          make config=release_x86_64
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: gmsv_steamworks_linux64
          path: projects/linux/gmake/x86_64/Release
